FROM openjdk:11.0.3
ADD ./target/spring-boot-neo4j-example-1-0.0.1-SNAPSHOT.jar spring-boot-neo4j-example-1-0.0.1-SNAPSHOT.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "spring-boot-neo4j-example-1-0.0.1-SNAPSHOT.jar"]
